# Generated by Django 5.0.6 on 2024-05-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(help_text='пункт навигации', max_length=50, verbose_name='пункт навигации')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Sublist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_sub_name', models.CharField(help_text='под пункт навигации', max_length=50, verbose_name='под пункт навигации')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='адресс')),
                ('nav_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.navbarlist', verbose_name='под пункты навигации')),
            ],
        ),
    ]
