# Generated by Django 5.0.6 on 2024-05-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarlist',
            options={'ordering': ['pk'], 'verbose_name': 'пункты', 'verbose_name_plural': 'пунк навигации'},
        ),
        migrations.AlterModelOptions(
            name='sublist',
            options={'verbose_name': 'пункты', 'verbose_name_plural': 'под пункты навигации'},
        ),
    ]
