# Generated by Django 5.0.6 on 2024-06-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='nav_main',
        ),
        migrations.DeleteModel(
            name='NavBarList',
        ),
        migrations.DeleteModel(
            name='Sublist',
        ),
    ]
