# Generated by Django 5.0.6 on 2024-05-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_message', models.CharField(max_length=100, verbose_name='заголовок сообщения')),
                ('text_message', models.TextField(verbose_name='содержимое сообщения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='время редактирования')),
                ('actual', models.BooleanField(default=True, verbose_name='актуальность')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeers', to=settings.AUTH_USER_MODEL, verbose_name='cоздатель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
