# Generated by Django 5.0.6 on 2024-05-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_messageinfo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageinfo',
            options={'ordering': ['-time_edit'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
