# Generated by Django 5.0.6 on 2024-05-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservise',
            name='client_middle_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='отчество клиента'),
        ),
    ]
