# Generated by Django 5.0.6 on 2024-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0003_clientservise_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservise',
            name='client_mail',
            field=models.EmailField(max_length=254, verbose_name='эмеил клиента'),
        ),
    ]
