# Generated by Django 5.0.6 on 2024-06-14 18:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess', '0003_alter_messageinfo_options'),
        ('our_clients', '0003_clientservise_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_send', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время первой отправки')),
                ('date_last_send', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время последней отправки')),
                ('periodicity', models.DurationField(choices=[(datetime.timedelta(seconds=900), 'Каждые пятнадцать минут'), (datetime.timedelta(seconds=1800), 'Каждый пол часа'), (datetime.timedelta(seconds=3600), 'Каждый час'), (datetime.timedelta(seconds=7200), 'Каждые два часа'), (datetime.timedelta(seconds=10800), 'Каждые три часа'), (datetime.timedelta(seconds=14400), 'Каждые четыре часа'), (datetime.timedelta(seconds=18000), 'Каждые пять часов'), (datetime.timedelta(seconds=21600), 'Каждые шесть часов'), (datetime.timedelta(seconds=43200), 'Каждые 12 часа'), (datetime.timedelta(days=1), 'Каждые сутки'), (datetime.timedelta(days=2), 'Каждые двое суток'), (datetime.timedelta(days=3), 'Каждые трое суток'), (datetime.timedelta(days=4), 'Каждые четыре суток'), (datetime.timedelta(days=5), 'Каждые пять суток'), (datetime.timedelta(days=6), 'Каждые шесть суток'), (datetime.timedelta(days=7), 'Каждую неделю'), (datetime.timedelta(days=14), 'Каждые две недели'), (datetime.timedelta(days=21), 'Каждые три недели'), (datetime.timedelta(days=30), 'Каждый месяц'), (datetime.timedelta(days=60), 'Каждые два месяца'), (datetime.timedelta(days=90), 'Каждые три месяца'), (datetime.timedelta(days=120), 'Каждые четыре месяца'), (datetime.timedelta(days=150), 'Каждые пять месяца'), (datetime.timedelta(days=180), 'Каждые пол года'), (datetime.timedelta(days=360), 'Каждый год')], default=(datetime.timedelta(days=1), 'Каждые сутки'), verbose_name='переодичность отправки')),
                ('status', models.CharField(choices=[('end', 'Завершено'), ('create', 'Созданно'), ('run', 'Запущено')], default='create', max_length=50)),
                ('clients', models.ManyToManyField(to='our_clients.clientservise', verbose_name='клиенты для рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.messageinfo', verbose_name='сообщения для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки сообщений',
                'ordering': ['-date_first_send', '-status'],
            },
        ),
    ]
