# Generated by Django 5.0.6 on 2024-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendingmessage',
            options={'ordering': ['-date_first_send'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки сообщений'},
        ),
        migrations.AlterField(
            model_name='sendingmessage',
            name='date_first_send',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время первой отправки'),
        ),
        migrations.AlterField(
            model_name='sendingmessage',
            name='periodicity',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='периодичность отправок'),
        ),
    ]
