# Generated by Django 5.0.6 on 2024-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0002_sendingmessage_owner_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsSendMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Результаты рассылки',
                'verbose_name_plural': 'Результаты Рассылки сообщений',
            },
        ),
    ]
