# Generated by Django 5.0.6 on 2024-05-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0002_alter_sendingmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendingmessage',
            options={'ordering': ['-date_first_send', '-status'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки сообщений'},
        ),
    ]
