# Generated by Django 5.0.6 on 2024-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0003_alter_sendingmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingmessage',
            name='date_last_send',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время последней отправки'),
        ),
    ]
