# Generated by Django 5.0.6 on 2024-06-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0005_alter_sendingmessage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmessage',
            name='status',
            field=models.CharField(choices=[('end', 'Завершено'), ('create', 'Созданно'), ('freeze', 'Заморожено'), ('run', 'Запущено')], default='create', max_length=50),
        ),
    ]
