# Generated by Django 5.0.6 on 2024-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0005_alter_sendingmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmessage',
            name='status',
            field=models.CharField(choices=[('end', 'Завершено'), ('create', 'Созданно'), ('run', 'Запущено')], max_length=50),
        ),
    ]
