# Generated by Django 5.0.6 on 2024-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_center', '0008_alter_resultssendmessages_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingmessage',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='отключение рассылки'),
        ),
        migrations.AlterField(
            model_name='sendingmessage',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
